// Learn more about DAX queries at https://aka.ms/dax-queries

// After adding data to this report, you can write your own DAX queries or run predefined ones
// by right clicking a table, column, or measure in the data pane and choosing one from 'Quick queries'
Define
measure [SLA Compliance Calls] = CALCULATE([SLA Compliance %], 'Table'[Interaction Type] = "Calls")

SLA Compliance Chats = CALCULATE([SLA Compliance %], 'Table'[Interaction Type] = "Chats")

SLA Compliance Emails = CALCULATE([SLA Compliance %], 'Table'[Interaction Type] = "Emails")

SLA Compliance Escalations = CALCULATE([SLA Compliance %], 'Table'[Interaction Type] = "Escalations")
